devices/schemas.yaml
This array of actions is essentially a "shortcut", saving one hash comparison and potentially one request to `devices/<dev_id>/actions`.
This is already how the `devices/<dev_id>` endpoint is implemented, the change is just to make the docs reflect the implementation.
=> Change device actions to an array

actions/paths.yaml
`number` -> `string` to match the actual implementation of this API.
`action_id` -> `action_name` for clarity's sake.
User request on the former: https://forum.bondhome.io/t/api-documentation-requests/278/11
=> Change action_id number to action_name string

common/paths.yaml, local/paths.yaml
CI was failing due to a few remaining references to `action_id`
=> Change all references of action_id to action_name

debug/rfman.yaml, debug/schemas.yaml, local/paths.yaml
I had copy-pasted from the LiveLog docs and there was still a reference to LiveLog.
This PR also clarifies that the "changes do not persist past reboot."
=> Fix RFMan documentation

common/schemas.yaml
This is to make the docs correct with respect to the implementation.
Why are these fields (`_error_id`, `_error_msg`, and `_id`) underscore-prefixed to begin with? What exactly do we want that underscore to convey?
User request: https://forum.bondhome.io/t/api-documentation-requests/278/16
=> Fix underscore-prefixed error fields

signal/schemas.yaml
This should fix the CI failures, `required` was not in the proper place in the Signal docs. (this was introduced here: https://github.com/bondhome/api-v2/commit/550370a712b9b3823ba944543d5e34b882d2b599)
=> Fix rendering of required and spec validation

commands/paths.yaml
Readers could find the form of the body in the PUT and PATCH, but not in the GET
=> Add Signal GET response body

common/info.yaml
no impact on HTTP API, since there the replies are only ever originating from the HTTP transport
=> Document source transport (x) field in BPUP and MQTT message schema

actions/paths.yaml
The devices/{}/actions/{} endpoints will now return a 200 and a copy of the request body, rather than a 204.
=> actions: PUT returns 200 and argument in body rather than 204

common/info.yaml, common/paths.yaml, local.yaml, local/paths.yaml, network/paths.yaml, network/schemas.yaml
Ethernet endpoint and related changes for Bond Bridge Pro (to be released as `v2.16` firmware).
Render: https://bond-api-docs.s3.amazonaws.com/merck-ethernet-local.html
=> add sys/eth; move sys/wifi/watchdog to sys/watchdog; make sys/eth, sys/wifi/sta PATCHable

network/paths.yaml, network/schemas.yaml
corresponding to bond-core implementation: https://github.com/ZolibraBond/bond-core/issues/1008
Should be reverse-compatible with apps. Current setup flow (PUT) does not need to change.
However, this new PATCH API is needed for the Network Settings screen to change IP / DNS config.
=> sys/eth, sys/wifi/sta: add PATCH support; static_ip_set, dns_set writeable

bridge/schemas.yaml, local.yaml, local/paths.yaml, locale/paths.yaml, locale/schemas.yaml
Purpose: so that SBB devices can have Australia region set for access to extra Wi-Fi channels.
=> sys/locale: move compliance_region field here

network/schemas.yaml
The preferred flag logic will be rremoved on the next bond firmware, this PR updates the documentation to reflect this change.
=> network: remove mention to the preferred flag of eth net interface

network/paths.yaml, network/schemas.yaml
As discussed, this changes the behavior of Wi-Fi not being set to return an object with a `not set` status, rather than returning a `null` object.
=> Add a 'not set' status to 'sys/wifi/sta'

common/paths.yaml, firmware/schemas.yaml, local/paths.yaml
@endy-s reported that the Backup endpoint docs were not visible. I'm not sure why `common/paths.yaml` is not being read. Anyways, moving to `local/paths.yaml` fixes the issue for now.
=> backup: fix visibility

actions/group-paths.yaml, groups/paths.yaml, groups/schemas.yaml, local.yaml, local/paths.yaml, skeds/group-paths.yaml
API for forthcoming Groups feature.
Highlights:
- create groups of devices within a single Bridge
- groups can be controlled in a very similar way to individual devices
- groups also support skeds
- actions available on a group are the intersection of the actions available on member devices
- multiple devices can be added in POST request (but this is not recommended, see note on POST groups)
- Group ID can be specified by client during POST request in `_id` field. See note on POST groups.
=> add Groups (on Bridges)

common/info.yaml, local/info.yaml
As of v3 firmware, Bond products have moved to 64-bit keys as resource identifiers, instead of the previous 32-bit keys. So, rather than a device being identified by an 8-digit hex string, the ids for newly created devices will be 16-digit hex strings.
In an effort to minimize distruption to API clients, already created resources (devices, commands, skeds, etc.) will continue to be represented using the same exact string on the API. Additional leading zeros will not be added. So, for example, a device with id `01abcdef` will continue to enumerate as `01abcdef` in v3. The Bond API is however liberal in what it accepts, removing leading zeros.
So any of the following received ids will be understood to point to this device: `1abcdef`, `01abcdef`, `0000000001abcdef`.
Internally, the Bond API …
=> Leading Zero Rule for 64-bit keys [v3]

devices/paths.yaml, devices/schemas.yaml, local.yaml, local/paths.yaml
We realized at Scrum call this morning that this documentation was missing.
=> PowerCycleState

groups/paths.yaml
after #67 
- attempting to create an empty group shard --> 400 Bad Request
- removing last device from group shard  --> group shard vanishes
by "vanish", I mean that the group shard is implicitly deleted.
[invited Fred, can tag him for review on these PRs once joined]
=> Disallow Empty Groups

groups/paths.yaml, groups/schemas.yaml, local/paths.yaml
We already have the following, which is used by the apps:
`POST groups/{}.devices`
`PATCH groups/{}.devices`
So the following redundant, unused endpoints are being removed:
`POST groups/{}/devices`  
`GET groups/{}/devices/{}`
`DELETE groups/{}/devices/{}`
=> groups: remove devices endpoints

local.yaml, local/paths.yaml, vrc/paths.yaml, vrc/schemas.yaml
=> VirtualRC: initial docs
