- common/info.yaml
Uncommon, but should be documented nonetheless.
> Document the StartIncreasingBrightness pair of actions

- common/paths.yaml
- local.yaml
- local/paths.yaml
- skeds/paths.yaml
- skeds/schemas.yaml
- sys/paths.yaml
- sys/schemas.yaml
Draft "skeds" API ahead of planned "Device Schedules" feature.
> Device Schedules

- token/paths.yaml
Requested here: https://forum.bondhome.io/t/chowmain-control4-integration-now-available/826/12?u=jacob
> Clarify PATCH token use cases

- common/info.yaml
DRAFT until we've completed the implementation.
> new Feature: LowEndTrim

- common/paths.yaml
- local.yaml
- local/paths.yaml
- sys/paths.yaml
- sys/schemas.yaml
> sys/power: USB/POE Power Supply active status

- common/info.yaml
> New Feature: ColorTemp

- bridge/paths.yaml
- bridge/schemas.yaml
> Bridge: add complaince_region, frequencies

- network/paths.yaml
- network/schemas.yaml
> sys/wifi/sta: remove 204 in favor of status=-4

- api/mqtt.yaml
https://github.com/ZolibraBond/bond-core/issues/1392
> api/mqtt: add enable

- api/bhk.yaml
- common/info.yaml
- common/paths.yaml
- local.yaml
- local/paths.yaml
BEFORE MERGING:
Add number on versions (right now it is v3.x.x)
Rendered: https://bond-api-docs.s3.us-east-1.amazonaws.com/endy-homekit-local.html
> Feature: HomeKit

- sidekicks/schemas.yaml
Tnx @jack-toast for reporting.
> sidekicks: _id is only for POST, not GET

- common/info.yaml
[no gamut issue. This is ready to go now.]
> new Features: RGB, RGBW

- sidekicks/paths.yaml
- sidekicks/schemas.yaml
> sidekicks: add .chan, .chan_links

- sidekicks/paths.yaml
- sidekicks/schemas.yaml
> sidekicks/x: add key_links and describe link fields in detail

- local.yaml
- local/paths.yaml
- sidekicks/paths.yaml
- sidekicks/schemas.yaml
@marciogranzotto requested documentation
> sidekicks/_learn: initial docs, mostly copied from devices/x/addr

- skeds/group-paths.yaml
- skeds/paths.yaml
This change is connected with the new policy to always request the user to set the timezone
> Update schedules documentation

- local.yaml
- local/paths.yaml
- weather_sensor/paths.yaml
- weather_sensor/schemas.yaml
Adds the Weather Sensor API endpoints.
Missing POST request as it conflicts with POST to sidekicks/
> Weather Sensor API

- actions/paths.yaml
- common/responses.yaml
- common/schemas.yaml
- devices/paths.yaml
- devices/schemas.yaml
Adds documentation for the _lock fields.
> DeviceLock: add documentation for the  _lock fields

- common/info.yaml
Added auto timer description at the Timer section.
> Timer: added auto timer doc

- common/info.yaml
Added Api doc for heat feature
> Heat: added heat feature api doc

- scenes/schemas.yaml
API for integrated and opaque Scenes.
> Scenes: integrated_from, opaque when actors missing
